// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend as main} from '../models';

export function AddDownloadTask(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string,arg6:string):Promise<main.DownloadTask>;

export function CancelDownloadTask(arg1:string):Promise<void>;

export function CancelRunningCommand():Promise<void>;

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function ClearCompletedDownloadTasks():Promise<void>;

export function ClearKeychainCache():Promise<void>;

export function DeleteDownloadTask(arg1:string):Promise<void>;

export function Download(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<main.DownloadResult>;

export function GetAccountInfo():Promise<main.AccountInfo>;

export function GetAppVersion():Promise<string>;

export function GetAccounts():Promise<Array<main.AccountInfo>>;

export function GetDownloadTasks():Promise<Array<main.DownloadTask>>;

export function GetSettings():Promise<main.Settings>;

export function GetThemeHintShown():Promise<boolean>;

export function GetVersionMetadata(arg1:string,arg2:string,arg3:number):Promise<main.VersionMetadataResult>;

export function InstallIPA(arg1:string,arg2:string):Promise<main.InstallResult>;

export function InspectIPA(arg1:string,arg2:string,arg3:string):Promise<main.IPAInspectionResult>;

export function ListDevices():Promise<Array<main.DeviceInfo>>;

export function ListPurchases(arg1:number,arg2:number):Promise<main.PurchasedResult>;

export function ListVersions(arg1:string,arg2:number):Promise<main.VersionsResult>;

export function MarkThemeHintShown():Promise<void>;

export function Login(arg1:string,arg2:string,arg3:string):Promise<main.LoginResult>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function PairDeviceForWiFi(arg1:string):Promise<boolean>;

export function Purchase(arg1:string):Promise<main.PurchaseResult>;

export function Revoke():Promise<boolean>;

export function RetryDownloadTask(arg1:string):Promise<main.DownloadTask>;

export function RemoveAccount(arg1:string):Promise<main.AccountInfo>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function Search(arg1:string,arg2:number,arg3:string):Promise<main.SearchResult>;

export function SelectDirectory(arg1:string,arg2:string):Promise<string>;

export function SelectIPA():Promise<string>;

export function SetKeychainPassphrase(arg1:string):Promise<void>;

export function SwitchAccount(arg1:string):Promise<main.AccountInfo>;

export function TestProxy(arg1:string):Promise<main.ProxyTestResult>;
