// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDownloadTask(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['backend']['App']['AddDownloadTask'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CancelDownloadTask(arg1) {
  return window['go']['backend']['App']['CancelDownloadTask'](arg1);
}

export function CancelRunningCommand() {
  return window['go']['backend']['App']['CancelRunningCommand']();
}

export function ClearCompletedDownloadTasks() {
  return window['go']['backend']['App']['ClearCompletedDownloadTasks']();
}

export function ClearKeychainCache() {
  return window['go']['backend']['App']['ClearKeychainCache']();
}

export function DeleteDownloadTask(arg1) {
  return window['go']['backend']['App']['DeleteDownloadTask'](arg1);
}

export function Download(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['backend']['App']['Download'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetAccountInfo() {
  return window['go']['backend']['App']['GetAccountInfo']();
}

export function GetAccounts() {
  return window['go']['backend']['App']['GetAccounts']();
}

export function GetDownloadTasks() {
  return window['go']['backend']['App']['GetDownloadTasks']();
}

export function GetSettings() {
  return window['go']['backend']['App']['GetSettings']();
}

export function GetVersionMetadata(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetVersionMetadata'](arg1, arg2, arg3);
}

export function InstallIPA(arg1, arg2) {
  return window['go']['backend']['App']['InstallIPA'](arg1, arg2);
}

export function ListDevices() {
  return window['go']['backend']['App']['ListDevices']();
}

export function ListPurchases(arg1, arg2) {
  return window['go']['backend']['App']['ListPurchases'](arg1, arg2);
}

export function ListVersions(arg1, arg2) {
  return window['go']['backend']['App']['ListVersions'](arg1, arg2);
}

export function Login(arg1, arg2, arg3) {
  return window['go']['backend']['App']['Login'](arg1, arg2, arg3);
}

export function OpenInExplorer(arg1) {
  return window['go']['backend']['App']['OpenInExplorer'](arg1);
}

export function Purchase(arg1) {
  return window['go']['backend']['App']['Purchase'](arg1);
}

export function Revoke() {
  return window['go']['backend']['App']['Revoke']();
}

export function PairDeviceForWiFi(arg1) {
  return window['go']['backend']['App']['PairDeviceForWiFi'](arg1);
}

export function RemoveAccount(arg1) {
  return window['go']['backend']['App']['RemoveAccount'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['backend']['App']['SaveSettings'](arg1);
}

export function Search(arg1, arg2, arg3) {
  return window['go']['backend']['App']['Search'](arg1, arg2, arg3);
}

export function SelectDirectory(arg1, arg2) {
  return window['go']['backend']['App']['SelectDirectory'](arg1, arg2);
}

export function SelectIPA() {
  return window['go']['backend']['App']['SelectIPA']();
}

export function SwitchAccount(arg1) {
  return window['go']['backend']['App']['SwitchAccount'](arg1);
}

export function TestProxy(arg1) {
  return window['go']['backend']['App']['TestProxy'](arg1);
}
