// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDownloadTask(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddDownloadTask'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CancelDownloadTask(arg1) {
  return window['go']['main']['App']['CancelDownloadTask'](arg1);
}

export function CancelRunningCommand() {
  return window['go']['main']['App']['CancelRunningCommand']();
}

export function ClearCompletedDownloadTasks() {
  return window['go']['main']['App']['ClearCompletedDownloadTasks']();
}

export function ClearKeychainCache() {
  return window['go']['main']['App']['ClearKeychainCache']();
}

export function DeleteDownloadTask(arg1) {
  return window['go']['main']['App']['DeleteDownloadTask'](arg1);
}

export function Download(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['Download'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetAccountInfo() {
  return window['go']['main']['App']['GetAccountInfo']();
}

export function GetDownloadTasks() {
  return window['go']['main']['App']['GetDownloadTasks']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVersionMetadata(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetVersionMetadata'](arg1, arg2, arg3);
}

export function ListPurchases(arg1, arg2) {
  return window['go']['main']['App']['ListPurchases'](arg1, arg2);
}

export function ListVersions(arg1, arg2) {
  return window['go']['main']['App']['ListVersions'](arg1, arg2);
}

export function Login(arg1, arg2, arg3) {
  return window['go']['main']['App']['Login'](arg1, arg2, arg3);
}

export function OpenInExplorer(arg1) {
  return window['go']['main']['App']['OpenInExplorer'](arg1);
}

export function Purchase(arg1) {
  return window['go']['main']['App']['Purchase'](arg1);
}

export function Revoke() {
  return window['go']['main']['App']['Revoke']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function Search(arg1, arg2, arg3) {
  return window['go']['main']['App']['Search'](arg1, arg2, arg3);
}

export function SelectDirectory(arg1, arg2) {
  return window['go']['main']['App']['SelectDirectory'](arg1, arg2);
}

export function TestProxy(arg1) {
  return window['go']['main']['App']['TestProxy'](arg1);
}
