// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelRunningCommand():Promise<void>;

export function ClearKeychainCache():Promise<void>;

export function Download(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<main.DownloadResult>;

export function GetAccountInfo():Promise<main.AccountInfo>;

export function GetSettings():Promise<main.Settings>;

export function GetVersionMetadata(arg1:string,arg2:string,arg3:number):Promise<main.VersionMetadataResult>;

export function ListPurchases(arg1:number,arg2:number):Promise<main.PurchasedResult>;

export function ListVersions(arg1:string,arg2:number):Promise<main.VersionsResult>;

export function Login(arg1:string,arg2:string,arg3:string):Promise<main.LoginResult>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function Purchase(arg1:string):Promise<main.PurchaseResult>;

export function Revoke():Promise<boolean>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function Search(arg1:string,arg2:number,arg3:string):Promise<main.SearchResult>;

export function SelectDirectory(arg1:string,arg2:string):Promise<string>;

export function TestProxy(arg1:string):Promise<main.ProxyTestResult>;
